package handler

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "ChoreCraft/docs" // docs is generated by Swag CLI
	"ChoreCraft/internal/model"
	"ChoreCraft/internal/service"
)

type contextKey string

const (
	userKey contextKey = "user"
)

// API holds the dependencies for the API handlers.
type API struct {
	service *service.Service
}

// New creates a new API instance.
func New(s *service.Service) *API {
	return &API{service: s}
}

// RegisterRoutes registers the API routes.
func (a *API) RegisterRoutes(r *chi.Mux) {
	r.Use(middleware.Logger)

	// Public routes
	r.Post("/api/signup", a.signup)
	r.Post("/api/login", a.login)
	r.Post("/api/users", a.addUser)
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// Protected routes
	r.Route("/api/households/{householdID}", func(r chi.Router) {
		r.Use(a.authMiddleware)
		r.Get("/tasks", a.listTasks)
		r.Post("/tasks", a.createTask)
		r.Post("/tasks/{taskID}/submit", a.submitTask)
		r.Get("/leaderboard", a.getLeaderboard)
		r.Get("/members", a.getHouseholdMembers) // New route for household members
		r.Get("/submissions", a.listSubmissions)
		r.Put("/tasks/{taskID}/status", a.updateTaskStatusByAdmin) // Changed route and handler
	})
}

// signup godoc
// @Summary      Sign up a new household and admin user
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        signup  body      model.SignUpRequest  true  "Signup Details"
// @Success      201     {object}  model.User
// @Router       /signup [post]
func (a *API) signup(w http.ResponseWriter, r *http.Request) {
	var req model.SignUpRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	user, err := a.service.SignUp(r.Context(), req.HouseholdName, req.Username, req.Password)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			http.Error(w, "Household or username already exists", http.StatusConflict)
			return
		}
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(user)
}

// login godoc
// @Summary      Log in a user
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        credentials  body      model.LoginRequest   true  "User Credentials"
// @Success      200          {object}  model.LoginResponse
// @Router       /login [post]
func (a *API) login(w http.ResponseWriter, r *http.Request) {
	var req model.LoginRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	res, err := a.service.Login(r.Context(), req.Username, req.Password)
	if errors.Is(err, service.ErrInvalidCredentials) {
		http.Error(w, "Invalid username or password", http.StatusUnauthorized)
		return
	} else if err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}
	json.NewEncoder(w).Encode(res)
}

// addUser godoc
// @Summary      Add a user to an existing household
// @Tags         Auth
// @Accept       json
// @Produce      json
// @Param        user  body      model.AddUserRequest  true  "User and Household Details"
// @Success      201   {object}  model.User
// @Router       /users [post]
func (a *API) addUser(w http.ResponseWriter, r *http.Request) {
	var req model.AddUserRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	user, err := a.service.AddUserToHousehold(r.Context(), req.HouseholdName, req.Username, req.Password, req.UserRole)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			http.Error(w, "User with this name already exists", http.StatusConflict)
			return
		}
		http.Error(w, "Household not found", http.StatusNotFound)
		return
	}
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(user)
}

// createTask godoc
// @Summary      Create a new task for a household
// @Description  Creates a new chore.
// @Tags         Tasks
// @Security     ApiKeyAuth
// @Accept       json
// @Produce      json
// @Param        X-User-ID    header    string                   true  "Admin User ID"
// @Param        householdID  path      string                   true  "Household ID"
// @Param        task         body      model.CreateTaskRequest  true  "Task details"
// @Success      201          {object}  model.Task
// @Router       /households/{householdID}/tasks [post]
func (a *API) createTask(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	if user.Role != "admin" {
		http.Error(w, "Forbidden: only admins can create tasks", http.StatusForbidden)
		return
	}
	var req model.CreateTaskRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	createdTask, err := a.service.CreateTask(r.Context(), user.HouseholdID, req)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(createdTask)
}

// listTasks godoc
// @Summary      List tasks for a household
// @Tags         Tasks
// @Security     ApiKeyAuth
// @Param        X-User-ID    header    string  true  "User ID"
// @Param        householdID  path      string  true  "Household ID"
// @Success      200          {array}   model.Task
// @Router       /households/{householdID}/tasks [get]
func (a *API) listTasks(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	tasks, err := a.service.ListTasks(r.Context(), user.HouseholdID, user.ID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	json.NewEncoder(w).Encode(tasks)
}

// submitTask godoc
// @Summary      Submit a task for approval
// @Tags         Tasks
// @Security     ApiKeyAuth
// @Param        X-User-ID    header    string  true  "User ID"
// @Param        householdID  path      string  true  "Household ID"
// @Param        taskID       path      string  true  "Task ID"
// @Success      201          {object}  model.TaskSubmission
// @Router       /households/{householdID}/tasks/{taskID}/submit [post]
func (a *API) submitTask(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	taskID, _ := uuid.Parse(chi.URLParam(r, "taskID"))
	submission, err := a.service.SubmitTask(r.Context(), taskID, user.ID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(submission)
}

// updateTaskStatusByAdmin godoc
// @Summary      Approve or reject a task by its ID
// @Tags         Admin
// @Security     ApiKeyAuth
// @Param        X-User-ID    header    string                       true  "Admin User ID"
// @Param        householdID  path      string                       true  "Household ID"
// @Param        taskID       path      string                       true  "Task ID"
// @Param        body         body      model.UpdateSubmissionRequest  true  "Action to perform (approve or reject)"
// @Success      204          {string}  string                       "No Content"
// @Failure      400          {string}  string                       "Bad Request"
// @Failure      403          {string}  string                       "Forbidden"
// @Failure      404          {string}  string                       "Not Found (e.g., task not found, no pending submission)"
// @Failure      409          {string}  string                       "Conflict (e.g., task already approved)"
// @Failure      500          {string}  string                       "Internal Server Error"
// @Router       /households/{householdID}/tasks/{taskID}/status [put]
func (a *API) updateTaskStatusByAdmin(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	taskID, err := uuid.Parse(chi.URLParam(r, "taskID"))
	if err != nil {
		http.Error(w, "Invalid task ID", http.StatusBadRequest)
		return
	}

	var req model.UpdateSubmissionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	err = a.service.UpdateTaskStatusByAdmin(r.Context(), user, taskID, req.Action)
	if errors.Is(err, service.ErrForbidden) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	} else if errors.Is(err, service.ErrTaskAlreadyApproved) {
		http.Error(w, err.Error(), http.StatusConflict) // 409 Conflict for already approved
		return
	} else if errors.Is(err, service.ErrNoPendingSubmission) {
		http.Error(w, err.Error(), http.StatusNotFound) // 404 Not Found if no pending submission
		return
	} else if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// getLeaderboard godoc
// @Summary      Get household leaderboard
// @Tags         Users
// @Security     ApiKeyAuth
// @Param        X-User-ID    header    string  true  "User ID"
// @Param        householdID  path      string  true  "Household ID"
// @Success      200          {array}   model.User
// @Router       /households/{householdID}/leaderboard [get]
func (a *API) getLeaderboard(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	users, err := a.service.GetLeaderboard(r.Context(), user.HouseholdID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	json.NewEncoder(w).Encode(users)
}

// getHouseholdMembers godoc
// @Summary      Get all members of a household
// @Tags         Users
// @Security     ApiKeyAuth
// @Param        X-User-ID    header    string  true  "User ID"
// @Param        householdID  path      string  true  "Household ID"
// @Success      200          {array}   model.User
// @Router       /households/{householdID}/members [get]
func (a *API) getHouseholdMembers(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	// The authMiddleware already ensures the user belongs to the householdID in the path
	members, err := a.service.GetHouseholdMembers(r.Context(), user.HouseholdID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	json.NewEncoder(w).Encode(members)
}

// authMiddleware fetches the user from the database and performs authorization.
func (a *API) authMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		userIDStr := r.Header.Get("X-User-ID")
		if userIDStr == "" {
			http.Error(w, "Unauthorized: Missing X-User-ID header", http.StatusUnauthorized)
			return
		}
		userID, err := uuid.Parse(userIDStr)
		if err != nil {
			http.Error(w, "Unauthorized: Invalid X-User-ID header", http.StatusUnauthorized)
			return
		}
		user, err := a.service.GetUserByID(r.Context(), userID)
		if err != nil {
			http.Error(w, "Unauthorized: User not found", http.StatusUnauthorized)
			return
		}
		if householdIDStr := chi.URLParam(r, "householdID"); householdIDStr != "" {
			householdID, _ := uuid.Parse(householdIDStr)
			if user.HouseholdID != householdID {
				http.Error(w, "Forbidden: You do not have access to this household", http.StatusForbidden)
				return
			}
		}
		ctx := context.WithValue(r.Context(), userKey, user)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// listSubmissions godoc
// @Summary      List submissions for a household
// @Tags         Admin
// @Security     ApiKeyAuth
// @Param        X-User-ID    header    string  true  "Admin User ID"
// @Param        householdID  path      string  true  "Household ID"
// @Success      200          {array}   model.TaskSubmission
// @Router       /households/{householdID}/submissions [get]
func (a *API) listSubmissions(w http.ResponseWriter, r *http.Request) {
	user := r.Context().Value(userKey).(model.User)
	if user.Role != "admin" {
		http.Error(w, "Forbidden: only admins can list submissions", http.StatusForbidden)
		return
	}
	submissions, err := a.service.ListSubmissions(r.Context(), user.HouseholdID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	json.NewEncoder(w).Encode(submissions)
}
